language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
before_install: "cpanm Module::Build::Prereqs::FromCPANfile"
script: "perl Build.PL; ./Build; perl -d:Trace t/simple_AnyEvent.t; perl -Iblib/lib -d:Trace t/Timeline.t"
