#!perl
use strict;
use warnings;

__END__

=pod

=head1 NAME

busybird - BusyBird runner script

=head1 SYNOPSIS

    ## read config file from ~/.busybird/config.psgi
    $ busybird

    ## explicit config file
    $ busybird another_config.psgi

    ## explicitly binding address/port
    $ busybird --host 0.0.0.0 --port 18888

=head1 DESCRIPTION

C<busybird> command runs a L<BusyBird> process instance.

=head1 OPTIONS

=over

=item -o,--host ADDRESS (default: 127.0.0.1)

IP address or hostname to listen.
By default, it listens to C<127.0.0.1>, meaning that it only accepts requests from the local machine.

=item -p,--port PORT (default: 5000)

TCP port number to listen.
By default, it listens to C<5000>.

=back

=head1 AUTHOR

Toshio Ito C<< toshioito [at] cpan.org >>

=cut

