=pod

=head1 NAME

BusyBird::Config - list of config parameters for BusyBird

=head1 SYNOPSIS

    Write synopsis(?)

=head1 DESCRIPTION

This document describes config parameters for L<BusyBird::Main> and L<BusyBird::Timeline>.

=head2 How to Set/Get Config Parameters

TBW. Keep in mind that users usually write configuration through L<BusyBird> interface.

=head2 Config Precedence

TBW

=head1 PARAMETERS FOR BusyBird::Main

=head2 C<default_status_storage> => BusyBird::StatusStorage OBJECT

B<Default:> L<BusyBird::StatusStorage::Memory> object.

A StatusStorage object used for Timelines by default.

A StatusStorage is an object where timelines save their statuses.
When a timeline is created by L<BusyBird::Main>'s C<timeline()> method, the default StatusStorage is used for the timeline.

Note that the default StatusStorage object is referred to only when creating timelines via C<timeline()> method.
Existing timelines are not affected by changing the default StatusStorage object.

A StatusStorage object is an implementation of L<BusyBird::StatusStorage> interface.
For example, the following modules can be used as StatusStorage.

=over

=item *

L<BusyBird::StatusStorage::Memory> - storage in the process memory

=back

See each module's documentation for details.


=head2 C<sharedir_path> => PATH

B<Default:> sharedir in your installation directory

File path to "share" directory.

"share" directory contains static files used by L<BusyBird>,
which include HTML templates, JavaScript files and image files.


=head1 PARAMETERS FOR BusyBird::Timeline


=head2 C<time_zone> => TIMEZONE_STR

B<Default:> C<"local">

Timezone used to render status timestamps.
C<TIMEZONE_STR> accepts various timezone names such as C<"UTC">, C<"America/Chicago">, C<"+0900">, C<"-0300">.

You can set special value C<"local"> to C<TIMEZONE_STR>.
This means the timezone of the local environment is used.

=head2 C<time_format> => STRFTIME_FORMAT_STR

B<Default:> C<"%x (%a) %X %Z">

Format used to render status timestamps.
The format string conforms to the C<strftime(3)> specification.

=head2 C<time_locale> => LOCALE_STR

B<Default:> C<LC_TIME> environment variable or C<"C">

Locale used to render status timestamps.

C<LOCALE_STR> is a valid locale string such as C<"en_US">, C<"ja_JP"> etc.

=head2 C<post_button_url> => URL_STR

B<Default:> C<"https://twitter.com/intent/tweet">

Link URL attached to the "Post" button in the navigation bar.

=head2 C<default_status_permalink_builder> => CODEREF($status)

B<Default:> build permalink to twitter.com

Subroutine reference that is supposed to build permalink URL to the status.

If the status has the C<busybird.status_permalink> field, that field is used for the permalink.
Otherwise, C<default_status_permalink_builder> is used to build the permalink.

The builder subroutine reference is called with the status object, as in:

    $url_str = $builder->($status)

C<$url_str> is a string.
If the result C<$url_str> is C<undef> or does not look like a valid URL, it is ignored.

=head2 C<urls_entity_url_builder> => CODEREF($entity, $status)

B<Default:> return C<< $entity->{display_url} >>

=head2 C<media_entity_url_builder> => CODEREF($entity, $status)

B<Default:> return C<< $entity->{display_url} >>

=head2 C<user_mentions_entity_url_builder> => CODEREF($entity, $status)

B<Default:> build URL to the user page of twitter.com

=head2 C<hashtags_entity_url_builder> => CODEREF($entity, $status)

B<Default> build URL to the hashtag search page of twitter.com

The above four configurations specify how L<Twitter Entities|https://dev.twitter.com/docs/platform-objects/entities>
in a status object generate link URLs attached to the status text.

The builder subroutine reference is called with the twitter entity object and the status object, as in:

    $url_str = $builder->($entity, $status)

C<$url_str> is a string.
If the result C<$url_str> is C<undef> or does not look like a valid URL, it is ignored, i.e., the text is not linked.



=head1 AUTHOR

Toshio Ito C<< <toshioito [at] cpan.org> >>

=cut

