=pod

=head1 NAME

BusyBird::Config - list of config parameters for BusyBird

=head1 SYNOPSIS

    Write synopsis(?)

=head1 DESCRIPTION

This document describes config parameters for L<BusyBird::Main> and L<BusyBird::Timeline>.

=head2 How to Set/Get Config Parameters

TBW. Keep in mind that users usually write configuration through L<BusyBird> interface.

=head2 Config Precedence

TBW

=head1 PARAMETERS FOR BusyBird::Main

=over

=item C<default_status_storage> => L<BusyBird::StatusStorage> OBJECT

B<Default:> L<BusyBird:StatusStorage::Memory> object.

A StatusStorage object used for Timelines by default.

A StatusStorage is an object where timelines save their statuses.
When a timeline is created by L<BusyBird::Main>'s C<timeline()> method, the default StatusStorage is used for the timeline.

Note that the default StatusStorage object is referred to only when creating timelines via C<timeline()> method.
Existing timelines are not affected by changing the default StatusStorage object.

A StatusStorage object is an implementation of L<BusyBird::StatusStorage> interface.
For example, the following modules can be used as StatusStorage.

=over

=item *

L<BusyBird::StatusStorage::Memory> - storage in the process memory

=back

See each module's documentation for details.


=item C<sharedir_path> => PATH

B<Default:> sharedir in your installation directory

File path to "share" directory.

"share" directory contains static files used by L<BusyBird>,
which include HTML templates, JavaScript files and image files.


=back


=head1 PARAMETERS FOR BusyBird::Timeline

=over

=item C<timezone> => TIMEZONE_STR

=item C<time_format> => STRPTIME_FORMAT_STR

=item C<urls_entity_display_key> => KEY_STR

=back


=head1 AUTHOR

Toshio Ito C<< <toshioito [at] cpan.org> >>

=cut

